Controllers/AutoPartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutomotiveCatalog.Data;
using AutomotiveCatalog.Models;

namespace AutomotiveCatalog.Controllers
{
    public class AutoPartsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AutoPartsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AutoParts
        public async Task<IActionResult> Index()
        {
              return _context.AutoParts != null ? 
                          View(await _context.AutoParts.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.AutoParts'  is null.");
        }
        // GET: AutoParts/ShowSearchForm
        public async Task<IActionResult> ShowPartsSearchForm()
        {
            return View();
        }
        // Post: AutoParts/ShowSearchResults
        //Метод който, чрез подаване на стрингова променлива, намира всички части за този модел
        public async Task<IActionResult> ShowPartsSearchResults(String SearchPhrase)
        {
            return View("Index", await _context.AutoParts.Where(j => j.VehicleFor.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: AutoParts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AutoParts == null)
            {
                return NotFound();
            }

            var autoParts = await _context.AutoParts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (autoParts == null)
            {
                return NotFound();
            }

            return View(autoParts);
        }

        // GET: AutoParts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AutoParts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Maker,Model,VehicleFor,Price")] AutoParts autoParts)
        {
            if (ModelState.IsValid)
            {
                _context.Add(autoParts);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(autoParts);
        }

        // GET: AutoParts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.AutoParts == null)
            {
                return NotFound();
            }

            var autoParts = await _context.AutoParts.FindAsync(id);
            if (autoParts == null)
            {
                return NotFound();
            }
            return View(autoParts);
        }

        // POST: AutoParts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Maker,Model,VehicleFor,Price")] AutoParts autoParts)
        {
            if (id != autoParts.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(autoParts);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutoPartsExists(autoParts.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(autoParts);
        }

        // GET: AutoParts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.AutoParts == null)
            {
                return NotFound();
            }

            var autoParts = await _context.AutoParts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (autoParts == null)
            {
                return NotFound();
            }

            return View(autoParts);
        }

        // POST: AutoParts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.AutoParts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.AutoParts'  is null.");
            }
            var autoParts = await _context.AutoParts.FindAsync(id);
            if (autoParts != null)
            {
                _context.AutoParts.Remove(autoParts);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AutoPartsExists(int id)
        {
          return (_context.AutoParts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutomotiveCatalog.Data;
using AutomotiveCatalog.Models;
using Microsoft.AspNetCore.Authorization;

namespace AutomotiveCatalog.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VehiclesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Vehiclecs
        public async Task<IActionResult> Index()
        {
            return _context.Vehiclecs != null ?
                        View(await _context.Vehiclecs.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Vehiclecs'  is null.");
        }
        // GET: Vehiclecs/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }
        // Post: Vehiclecs/ShowSearchResults
        //Метод който, чрез подаване на стрингова променлива, намира модел от Vehiclecs и подава нужната информация от листа с превозни средства
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("Index", await _context.Vehiclecs.Where(j => j.Model.Contains(SearchPhrase)).ToListAsync());
        }


        // GET: Vehiclecs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vehiclecs == null)
            {
                return NotFound();
            }

            var vehiclecs = await _context.Vehiclecs
                .FirstOrDefaultAsync(m => m.ID == id);
            if (vehiclecs == null)
            {
                return NotFound();
            }

            return View(vehiclecs);
        }

        // GET: Vehiclecs/Create
         
     
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vehiclecs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Maker,Model,ProductionYear,Displacement,Power,TopSpeed")] Vehicles vehiclecs)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vehiclecs);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vehiclecs);
        }

        // GET: Vehiclecs/Edit/5
       
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vehiclecs == null)
            {
                return NotFound();
            }

            var vehiclecs = await _context.Vehiclecs.FindAsync(id);
            if (vehiclecs == null)
            {
                return NotFound();
            }
            return View(vehiclecs);
        }

        // POST: Vehiclecs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Maker,Model,ProductionYear,Displacement,Power,TopSpeed")] Vehicles vehiclecs)
        {
            if (id != vehiclecs.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehiclecs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehiclecsExists(vehiclecs.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehiclecs);
        }

        // GET: Vehiclecs/Delete/5
      
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vehiclecs == null)
            {
                return NotFound();
            }

            var vehiclecs = await _context.Vehiclecs
                .FirstOrDefaultAsync(m => m.ID == id);
            if (vehiclecs == null)
            {
                return NotFound();
            }

            return View(vehiclecs);
        }

        // POST: Vehiclecs/Delete/5
         
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vehiclecs == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Vehiclecs'  is null.");
            }
            var vehiclecs = await _context.Vehiclecs.FindAsync(id);
            if (vehiclecs != null)
            {
                _context.Vehiclecs.Remove(vehiclecs);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehiclecsExists(int id)
        {
          return (_context.Vehiclecs?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutomotiveCatalog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AutomotiveCatalog.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutomotiveCatalog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="Index">VehicleCatalog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="ShowSearchForm">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AutoParts" asp-action="Index">AutoParts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AutoParts" asp-action="ShowPartsSearchForm">PartsforVehicle</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AutomotiveCatalog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>